name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get Dependencies
        run: flutter pub get
      - name: Format
        run: dart format --set-exit-if-changed .
      - name: Lint
        run: flutter analyze --fatal-infos --fatal-warnings